CREATE TABLE IF NOT EXISTS leaderboard(
    id INTEGER PRIMARY KEY,
    num_msg INTEGER NOT NULL,
    xp INTEGER NOT NULL,
    timestamp INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS welcoming(
    user_id INTEGER PRIMARY KEY,
    msg_id INTEGER
);