#ifndef DISCORD_INTERACTIONFWD_H
#define DISCORD_INTERACTIONFWD_H
#include "BaseFwd.h"
DISCORD_FWDDECL_CLASS(Interaction);
DISCORD_FWDDECL_CLASS(AppCmdInteraction);
DISCORD_FWDDECL_CLASS(MsgCompInteraction);
DISCORD_FWDDECL_CLASS(ModalSubmitInteraction);
#endif /* DISCORD_INTERACTIONFWD_H */