#ifndef DISCORD_COMPONENTFWD_H
#define DISCORD_COMPONENTFWD_H
#include "BaseFwd.h"

DISCORD_FWDDECL_STRUCT(ActionRow);
DISCORD_FWDDECL_CLASS(Button);
DISCORD_FWDDECL_STRUCT(Label);
DISCORD_FWDDECL_STRUCT(PartialLabel);
DISCORD_FWDDECL_STRUCT(PartialTextInput);
DISCORD_FWDDECL_CLASS(SelectMenu);
DISCORD_FWDDECL_CLASS(TextDisplay);
DISCORD_FWDDECL_CLASS(TextInput);
DISCORD_FWDDECL_CLASS(UnsupportedComponent);
#endif //DISCORD_COMPONENTFWD_H