#ifndef DISCORD_EMBEDFWD_H
#define DISCORD_EMBEDFWD_H
#include "BaseFwd.h"
DISCORD_FWDDECL_CLASS(Embed);
DISCORD_FWDDECL_CLASS(EmbedAuthor);
DISCORD_FWDDECL_CLASS(EmbedField);
DISCORD_FWDDECL_CLASS(EmbedFooter);
DISCORD_FWDDECL_CLASS(EmbedMedia);
#endif /* DISCORD_EMBEDFWD_H */