#ifndef DISCORD_MEMBERFWD_H
#define DISCORD_MEMBERFWD_H
#include "UserFwd.h"
DISCORD_FWDDECL_CLASS(MemberOptions);
DISCORD_FWDDECL_CLASS(MemberUpdate);
DISCORD_FWDDECL_CLASS(PartialMember);
DISCORD_FWDDECL_CLASS(Member);
#endif /* DISCORD_MEMBERFWD_H */